version: '3.3'

services:
  mongo-db:
    image: mongo:6.0
    container_name: mongo-flow
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-secret}
    ports:
      - ${MONGO_PORT:-27016}:27017
    